name: LionNet
author: Maciej Lew
url: http://lion.net.pl
description: Progra&shy;mowanie, sieci kompu&shy;terowe, informa&shy;tyka.
disqus-id: lionnetpl
email: maciej.lew.1987 [at] gmail.com
github: maciejlew
timezone: Europe/Warsaw
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
