name: LionNet
author: Maciej Lew
url: http://lion.net.pl
description: Programowanie, sieci komputerowe, informatyka.
disqus-id: lionnetpl
email: maciej.lew.1987 [at] gmail.com
github: maciejlew
timezone: Europe/Warsaw
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist