name: lion.net.pl
description: Progra&shy;mowanie, sieci kompu&shy;terowe, informa&shy;tyka.
markdown: kramdown
highlighter: true
disqus-id: lionnetpl
email: maciej.lew.1987 [at] gmail.com
github: maciejlew
gems:
  - jekyll-sitemap
  