name: LionNet
author: Maciej Lew
url: http://lion.net.pl
description: Programowanie, sieci komputerowe, informatyka.
disqus-id: lionnetpl
email: maciej.lew.1987 [at] gmail.com
github: maciejlew
timezone: Europe/Warsaw
date: "2014-06-19"
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-seo-tag